version: '3.9'

services:
  product_service:
    build: 
      context: ./Product
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "python main.py"
    volumes:
      - ./Product/app:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${PRODUCT_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - zookeeper
      - kafka
      
  order_service:
    build: 
      context: ./Order
    restart: always
    ports:
      - "8001:8001"
    command: >
      sh -c "python main.py"
    volumes:
      - ./Order/app:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${ORDER_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - zookeeper
      - kafka
      
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product_service
      - order_service

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2.8
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

volumes:
  postgres-data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local